nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'http://192.168.2.1:3000']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://linos.store', 'http://localhost:3000', 'http://192.168.2.1:3000']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600